Ignoring requests containing list instead of dict
I had problems sending list as json object to DRF, oauth2_provider were raising this error:

```
File ".../lib/python3.6/site-packages/oauth2_provider/oauth2_backends.py", line 183, in extract_body
    body = json.loads(request.body.decode('utf-8')).items()
AttributeError: 'list' object has no attribute 'items'
```

It's solved by this commit.